(new TestArrayComp()).run();

/** Syntax
 *    "[" expr "|" assign [ "," ( assign | predicate ) ]* "]"
 *      where
 *        assign    := SYMBOL "in" expr
 *        predicate := expr
 *
 ** Sementics
 *    the code:
 *      var a = [ expr1 | x in expr2, y in expr3, pred ]
 *    is syntactic sugar of:
 *      var a;
 *      {
 *        var x;
 *        var $1 = [];
 *        var $2 = Iterator.from(expr2);
 *        while ($2.moveNext()) {
 *          x = $2.current();
 *          var y;
 *          var $3 = Iterator.from(expr3);
 *          while ($3.moveNext()) {
 *            y = $3.current();
 *          }
 *          if (!pred) continue;
 *          $1.add(expr1);
 *        }
 *        a = $2;
 *      }
 */

class TestArrayComp extends Test {
  
  var name = 'ARRAY COMPREHENSION';
  var tests = [
    'test_syntax',
    'test_scope'
  ];
  
  function test_syntax {
    [ x | x in [10,20,30] ];
    [ x * 2 | x in [10,20,30] ];
    
    var array = [10,20,30];
    [ x | x in array ];
    [ x * 2 | x in array ];
    
    [ x * y | x in array, y in array ];
    [ x * y | x in array, y in array, z in array ];
    
    [ x | x in array, x % 20 == 0 ];
    [ x * y | x in array, x % 20 == 0, y in array, z in array ];
  }
  
  function test_scope {
    var x = void, y = void;
    [ x | x in [10,20,30] ];
    assert_equal(x, void, '1');
    
    [ x * y | x in [10,20,30], y in [40, 50, 60] ];
    assert_equal(x, void, '1');
    assert_equal(y, void, '1');
  }
  
  function test_main {
    var a = [ x | x in [10,20,30] ];
    assert_equal_struct(a, [10,20,30], '1');
    
    a = [ x * 2 | x in [10,20,30] ];
    assert_equal_struct(a, [20,40,60], '2');
    
    var array = [10,20,30];
    a = [ x | x in array ];
    assert_equal_struct(a, [10,20,30], '3');
    
    a = [ x * 2 | x in array ];
    assert_equal_struct(a, [20,40,60], '4');
    
    var array1 = [2,3,4];
    var array2 = [5,6,7];
    a = [ x * y | x in array1, y in array2 ];
    assert_equal_struct(a, [10,12,14,15,18,21,20,24,28], '5');
    
    a = [ x | x in array, x % 20 == 0 ];
    assert_equal_struct(a, [20], '6');
    
    a = [ x * y | x in array, x % 20 != 0, y in array ];
    assert_equal_struct(a, [100,200,300,300,600,900], '7');
    
    a = [ x * y | x in array, x % 20 != 0, y in array, y % 20 == 0 ];
    assert_equal_struct(a, [200,600], '8');
  }
  
}
