//var a = |x| -> { x; };
//var b = x -> { return x; };
//System.inform(b(1));
//var a = function(i) { return i*5; };
//System.inform(a(1));
//System.inform(Scripts.exec("var b = x -> { x; };"));
// -> null;System.exit();/*
//class A{}
//var a = A();
//var b = new A();
//System.inform(a);
//System.inform(b);
//var c = new A()();
//System.inform(c);

function assert(b, str="") {
    if (b) return true;
    throw new Exception(str);
}

function assert_raise(fn, str="") {
  try { fn(); } catch (e) { return true; }
  throw new Exception(str);
}

function simple_equals(ary1, ary2) {
  if (ary1.count != ary2.count) return false;
  for (var i = 0, e = ary1.count; i < e; ++i)
    if (ary1[i] !== ary2[i]) return false;
  return true;
}

Scripts.execStorage("array_functions.tjs");
Scripts.execStorage("arrow.tjs");
//*/