class Test {
  
  var tests = [];
  var name;
  
  function Test(name) {
    this.name = name;
  }
  
  function toString(obj) {
    if (obj === void) return 'void';
    if (obj === null) return 'null';
    if (obj instanceof 'Array') {
      var items = [];
      for (var i = 0, e = obj.count; i <e; ++i) items.add(toString(obj[i]));
      return @'[${items.join(", ")}]';
    }
    if (obj instanceof 'Dictionary') {
      var keys = obj->keys();
      var items = [];
      for (var i = 0, e = keys.count; i < e; ++i) items.add(@'${keys[i]}: ${toString(obj[keys[i]])}');
      return @'%[${items.join(", ")}]';
    }
    return (string)obj;
  }
  
  function puts(str) {
    Debug.message(str);
  }
  
  function equal_struct(obj1, obj2) {
    if ((typeof obj1) !== (typeof obj2))
      return false;
    switch (typeof obj1) {
    case 'void': return true;
    case 'Integer':
    case 'Real':
    case 'String':
      return obj1 === obj2;
    case 'Object':
      if (obj1 === null || obj2 === null) {
        return (obj1 === null) && (obj2 === null);
      }
      if (obj1 instanceof 'Array' && obj2 instanceof 'Array') {
        if (obj1.count !== obj2.count) return false;
        for (var i = 0, e = obj1.count; i < e; ++i) {
          if (!equal_struct(obj1[i], obj2[i])) return false;
        }
        return true;
      }
      if (obj1 instanceof 'Dictionary' && obj2 instanceof 'Dictionary') {
        var a1 = [], a2 = [];
        a1.assign(obj1);
        a2.assign(obj2);
        if (a1.count != a2.count) return false;
        var key1 = a1.filter(-> (x, i) [ i % 2 == 0 ]);
        var key2 = a2.filter(-> (x, i) [ i % 2 == 0 ]);
        key1.sort(); key2.sort();
        if (!equal_struct(key1, key2)) return false;
        for (var i = 0, e = key1.count; i < e; ++i) {
          if (!equal_struct(obj1[key1[i]], obj2[key1[i]])) return false;
        }
        return true;
      }
      //throw new Exception('Object: Not Implemented');
      return false;
    case 'Octet':
      throw new Exception('Octet: Not Implemented');
    default:
      throw new Exception('must not happen!');
    }
  }
  
  function assert(v, str='') {
  	if (v) return true;
  	str = str.length ? @'${str}: ' : '';
  	throw new Exception(@'${str}assertion failed');
  }
  
  function assert_equal(v, expected, str='') {
    if (v === expected) return true;
    v = toString(v);
    var ex = toString(expected);
    str = str.length ? @'${str}: ' : '';
    throw new Exception(@'${str}${ex} is expected, but ${v}');
  }
  
  function assert_not_equal(v, not_expected, str='') {
    if (v !== not_expected) return true;
    v = toString(v);
    var ex = toString(not_expected);
    str = str.length ? @'${str}: ' : '';
    throw new Exception(@'${str}${ex} is not expected, but ${v}');
  }
  
  function assert_throw(fn, str='') {
    try { fn(); } catch { return true; }
    throw new Exception(str);
  }
  
  function assert_array_equal(v, expected, str='') {
    var str1 = str.length ? @'${str}: ' : '';
    if (!(v instanceof 'Array') || !(expected instanceof 'Array'))
      throw new Exception(@'${str1}non-array object given');
    if (v.count !== expected.count)
      throw new Exception(@'${str1}expected length is ${expected.count}, but ${v.count}');
    for (var i = 0, e = v.count; i < e; ++i) {
      var x = v[i];
      var y = expected[i];
      if (x instanceof 'Array') {
        assert_array_equal(x, y, str);
      } else if (x !== y) {
        throw new Exception(@'${str1}[at index ${i}] ${toString(y)} is expected, but ${toString(x)}');
      }
    }
    return true;
  }
  
  function assert_equal_struct(v, expected, str='') {
    if (equal_struct(v, expected)) return true;
    if (v === expected) return true;
    v = toString(v);
    var ex = toString(expected);
    str = str.length ? @'${str}: ' : '';
    throw new Exception(@'${str}${ex} is expected, but ${v}');
  }
  
  function setup() { }
  
  function teardown() { }
  
  function run() {
    puts(@'@@@ TEST ${name} ==============================');
    var result = [];
    for (var i = 0; i < tests.count; ++i) {
      setup();
      var test = tests[i];
      try {
        this[test]();
        result.add([true, @'\033[32m  ${test}: success\033[0m']);
      } catch (e) {
        result.add([false, @'\033[31m  ${test}: ${e.message}\033[0m']);
      }
    }
    teardown();
    for (var i = 0; i < result.count; ++i) puts(result[i][1]);
    var ok = result.filter(-> x [ x[0] ]).count;
    var fail = result.filter(-> x [ !x[0] ]).count;
    if (fail === 0) {
      puts('\033[32m  SUCCESS ALL TESTS\033[0m');
    } else {
      puts(@'\033[31m  FAIL ${fail} TESTS\033[0m');
    }
    puts(@'$$$ TEST ${name} ==============================');
  }
}
